### ISSUE TITLE
Blank white page during installation at step 3

### ISSUE THREAD

**Issue by Unnamed2025** [ex-url/exopencart#1]
Hey there! 
First, I just want to thank you for the awesome work you’ve done!

I ran into a little hiccup during the installation. In step 3, I'm getting a white page, but I can see that the database tables are still being created. 

I’ve tried it out on PHP versions 7.3 and 7.4. Any help would be super appreciated! Thanks again!

**Comment by ex-url** [comment]
Hi!
Thank you for the feedback! Glad you like it :)
Unfortunately I can't reproduce any errors while the installation process (made two of them today with the latest distribution), so I assume it's something about configuration of your server. If you can try to install it on different one, it could proves that the problem is about environment. It works as expected on several shared hosting accounts on different hosting providers and on localhost with devilbox. 
Best regards, 
Eugene 
Saturday, 09 November 2024, 08:56PM +04:00 from Nim2022  ***@***.*** :

**Comment by Unnamed2025** [comment]
I figured it out; it's related to MySQL version 8.0.
